stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t django-test .
    - echo "docker image built"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - docker network create my-django-network || docker run --env-file .env --name django-test -p 8080:8080 --network my-django-network -d django-test
    - echo "docker container started"
