# Generated by Django 2.2 on 2023-04-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price_from', models.PositiveIntegerField(verbose_name='цена от')),
                ('price_to', models.PositiveIntegerField(verbose_name='цена до')),
                ('place', models.CharField(blank=True, max_length=75, verbose_name='место')),
                ('term', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='заказчик')),
            ],
        ),
    ]
