# Generated by Django 2.2 on 2023-04-11 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price_from', models.PositiveIntegerField(verbose_name='цена от')),
                ('price_to', models.PositiveIntegerField(verbose_name='цена до')),
                ('place', models.TextField(blank=True, verbose_name='место')),
                ('term', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.Category', verbose_name='категория')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('watched', models.BooleanField(default=False, verbose_name='просмотрено')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.ServiceRequest', verbose_name='запрос на услугу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
        ),
    ]
