# Generated by Django 2.2 on 2023-04-10 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('watched', models.BooleanField(default=False, verbose_name='просмотрено')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.ServiceRequest', verbose_name='запрос на услугу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
        ),
    ]
