# Generated by Django 2.2 on 2023-04-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='в архиве'),
        ),
    ]
