# Generated by Django 2.2 on 2023-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_serviceresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='place',
            field=models.TextField(blank=True, verbose_name='место'),
        ),
    ]
