# Generated by Django 2.2 on 2023-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230412_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresponse',
            name='image',
            field=models.ImageField(blank=True, upload_to='response_images/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='serviceresponse',
            name='video',
            field=models.URLField(blank=True, max_length=100, verbose_name='ссылка на видео'),
        ),
    ]
