from django.urls import path
from . import views


urlpatterns = [
     path('', 
          views.MainView.as_view(),
          name='main'),
     path('info/', 
          views.InfoView.as_view(),
          name='info'),
     path('notifications/',
          views.NotificationsView.as_view(),
          name='notifications'),
     path('requests/', 
          views.ServiceRequestListView.as_view(), 
          name='request_list'),
     path('requests/<int:pk>/', 
          views.ServiceRequestDetailView.as_view(), 
          name='request_detail'),
     path('requests/filter/<int:pk>', 
          views.ServiceRequestListView.as_view(), 
          name='request_list_filtered'),
     path('requests/create/', 
          views.ServiceRequestCreateView.as_view(), 
          name='request_create'),
     path('my_requests/', 
          views.MyRequestsListView.as_view(),
          name='my_requests'),
     path('my_requests/edit/<int:pk>/', 
          views.ServiceRequestEditView.as_view(), 
          name='my_requests_edit'),
     path('my_requests/delete/<int:pk>/', 
          views.ServiceRequestDeleteView.as_view(), 
          name='my_requests_delete'),
     path('my_requests/achived/<int:pk>/', 
          views.ServiceRequestArchivedView.as_view(), 
          name='my_requests_archived'),
     path('responses/',
          views.ServiceResponseListView.as_view(),
          name='response_list'),
     path('responses/<int:pk>/',
         views.ServiceResponseDetailView.as_view(),
         name='response_detail'),
     path('responses/create/<int:pk>/',
         views.ServiceResponseCreateView.as_view(), 
         name='response_create'),
]